Feat/staking cli
sedaprotocol/seda-overlay pull request #53
Opened 2023-09-25 20:41 UTC by mennatabuelnaga

Added 4 CLI commands:
1- `make run-build node info` call get_data_request_executor to display node info.
2- `make run-build node stake <AMOUNT>` if the executor isn't registered yet, it registers it, else it calles deposit_and_stake to stake more tokens.
3- `make run-build node un-stake <AMOUNT>` unstakes the specified amount of tokens.
4- `make run-build node withdraw <AMOUNT> withdraws the specified unstaked amount of tokens` 

Tests:
Manually tested all commands on devnet

2023-09-25 21:52 UTC, gluax requested changes

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/info/mod.rs
> +        let payload_json_string = object! {
There's a `json` macro in serde_json that does the same thing :)

2023-09-25 21:52 UTC, gluax commented on cli/Cargo.toml
> +json = "0.12.4"
Maybe unnecessary. Either way put in the workspace and then `workspace = true`.

2023-09-25 21:52 UTC, gluax commented on cli/Cargo.toml
> +schemars = "0.8.10"
Same thing, move to workspace :).

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/info/mod.rs
> +pub struct Info {}
Can just do `pub struct Info;`

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/info/mod.rs
> +        let inner_config = config.seda_chain.clone().to_config(config.seda_chain.clone()).unwrap();
Use `?` operator instead of `unwrap` or map errors if necessary :).

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/stake/mod.rs
> +        let inner_config = config.seda_chain.clone().to_config(config.seda_chain.clone()).unwrap();
Same here handle the unwraps!

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/unstake/mod.rs
> +        let inner_config = config.seda_chain.clone().to_config(config.seda_chain.clone()).unwrap();
Unwraps.

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/withdraw/mod.rs
> +        let inner_config = config.seda_chain.clone().to_config(config.seda_chain.clone()).unwrap();
We shouldn't need to clone these that much. Should be able to move them. i.e. be able to do this without the clones.

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/withdraw/mod.rs
> +        let contract_address = config.seda_chain.clone().contract.unwrap();
Same here! Or maybe a reference in this case.

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/withdraw/mod.rs
> +        let inner_config = config.seda_chain.clone().to_config(config.seda_chain.clone()).unwrap();
Ah, I think it's cause this one requires the config, right? Then we should be passing it down and have the cli args... there should be some commands with examples of this.

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/withdraw/mod.rs
> +        println!("**exec contract value: {:?}", response);
Does this give some JSON format back that we can print? to make it more human-readable

2023-09-25 21:52 UTC, gluax commented on cli/src/cli/commands/node/withdraw/mod.rs
> +    pub async fn handle(self, config: AppConfig) -> Result<()> {
Unwraps!

2023-09-26 07:36 UTC, FranklinWaller requested changes

2023-09-26 07:36 UTC, FranklinWaller commented on cli/Cargo.toml
> +json = "0.12.4"
Preferably use serde-json

2023-09-26 07:36 UTC, FranklinWaller commented on cli/src/cli/commands/node/info/mod.rs
> +        let payload_json_string = object! {
in `seda-common` we have the actual types for these (see `contract.rs`)

2023-09-26 07:36 UTC, FranklinWaller commented on cli/src/cli/commands/node/stake/mod.rs
> +    pub tokens_pending_withdrawal: String, // u128 throws Error("invalid number")
Package `primitive-types` has a `U128` which should be able to be handled by CLI

2023-09-26 07:36 UTC, FranklinWaller commented on cli/Cargo.toml
> +schemars = "0.8.10"
Why do we need schemars? I think `serder-json` is fine in most cases

2023-09-26 07:36 UTC, FranklinWaller commented on cli/src/cli/commands/node/unstake/mod.rs
> +        let payload_json_string = object! {
Replace with `seda-common`

2023-09-26 07:36 UTC, FranklinWaller commented on cli/src/cli/commands/node/stake/mod.rs
> +pub struct GetDataRequestExecutorResponse {
It's best to also put this in `seda-common` contract

2023-09-26 09:07 UTC, FranklinWaller commented
It's maybe good to have the prinln's not use `:?` or debug formatting and print them in a formatted way so it's nice for the user to read

2023-09-26 13:59 UTC, jamesondh commented on cli/src/cli/commands/node/mod.rs
> +    UnStake(UnStake),
We should use "Unstake" or "unstake" as opposed to "UnStake" or "un-stake"

2023-09-27 09:22 UTC, FranklinWaller requested changes
Very nice! A few minor things.
The only thing is that the output is still pretty raw from the CLI. (Since it's just outputting the response) What a user expects is more in the lines of:

```
Your address: ADDRESS
Amount staked: 10 SEDA (10000000000000aSEDA)
P2P Multi address: MULTI_ADDRESS
```

And similar for the other commands

2023-09-27 09:22 UTC, FranklinWaller commented on Cargo.toml
> +# schemars = "0.8"
Comment

2023-09-27 09:22 UTC, FranklinWaller commented on cli/Cargo.toml
> +cosmrs = { workspace = true }
I don't think this package is used anymore

2023-09-27 09:22 UTC, FranklinWaller commented on cli/src/cli/commands/node/info/mod.rs
> +// use json::object;
Comment

2023-10-02 07:50 UTC, FranklinWaller approved these changes

2023-10-02 12:12 UTC, FranklinWaller requested changes

2023-10-02 12:12 UTC, FranklinWaller commented on cli/src/cli/commands/node/info/mod.rs
> +        let val = value.value.as_ref().unwrap();
This fails when the node never registered, should be some error that the user has no entry in the registry

2023-10-02 12:17 UTC, FranklinWaller commented on cli/src/cli/commands/node/unstake/mod.rs
> +            "Unstaking execution result: {:?}",
This is not really readable, this should be nicely formatted with a success/reject depending on the response. (I've tried to unstake when im not registered as a test)
<img width="1663" alt="Screenshot 2023-10-02 at 14 17 03" src="https://github.com/sedaprotocol/seda-overlay/assets/5691892/ae7ffba5-5de8-4833-8c5f-19fbed81ed9c">

2023-10-02 12:18 UTC, FranklinWaller commented on cli/src/cli/commands/node/unstake/mod.rs
> +    amount:          u128, // in seda
I cannot stake/unstake 0.01 SEDA, this results in an error

2023-10-02 12:21 UTC, FranklinWaller commented on cli/src/cli/commands/node/info/mod.rs
> +        println!("p2p_multi_address: {:?}", val.p2p_multi_address);
```suggestion
        println!("p2p_multi_address: {}", val.p2p_multi_address.unwrap_or("None provided"));
```

2023-10-02 12:47 UTC, mariocao commented on cli/src/cli/commands/node/info/mod.rs
> +        let val = value.value.as_ref().unwrap();
Same
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/src/cli/commands/node/info/mod.rs:35:40
```

2023-10-02 12:53 UTC, mariocao commented on cli/src/cli/commands/node/unstake/mod.rs
> +    amount:          u128, // in seda
Maybe in the future we would like to have the possibility to unstake or withdraw everything...instead of asking the user to know how much. But for now it is okay. :P

2023-10-03 08:40 UTC, FranklinWaller commented on cli/src/cli/commands/node/stake/mod.rs
> +        println!(
Debug stuff, can be removed

2023-10-03 08:45 UTC, FranklinWaller commented on cli/src/cli/commands/node/stake/mod.rs
> +            if response.deliver_tx.log.contains("failed to execute message") {
Is there a status code or something that we can use? Looking in the logs to see if it failed is prone to break

2023-10-03 08:46 UTC, FranklinWaller commented on common/src/contract.rs
> +// use primitive_types::U128;
Don't we still need this instead of type U128?

2023-10-03 09:12 UTC, mennatabuelnaga commented on common/src/contract.rs
> +// use primitive_types::U128;
No, for some reason primitive_types::U128 throws an error when executing any call. It g8ves an invalid type error.

2023-10-03 09:13 UTC, mennatabuelnaga commented on cli/src/cli/commands/node/stake/mod.rs
> +            if response.deliver_tx.log.contains("failed to execute message") {
No there's not. Logs is the only way I found to check tx failure.

2023-10-03 09:25 UTC, FranklinWaller commented on cli/src/cli/commands/node/stake/mod.rs
> +            if response.deliver_tx.log.contains("failed to execute message") {
`response.deliver_tx.code` looks like the desired one.

Either returns `response.deliver_tx.code = Ok` or `response.deliver_tx.code = Err(
    5,
)`

So you can do a is_ok or is_err

2023-10-07 10:00 UTC, mariocao requested changes
Rebase needed as there is a conflict in `config/src/configs/chains/seda.rs`, more specifically in the function `derive_private_key(mnemonic_phrase: &str)`.

2023-10-09 07:15 UTC, FranklinWaller approved these changes

2023-10-09 09:08 UTC, merged